// <auto-generated />
using System;
using BodyMeasurementsTrackerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BodyMeasurementsTrackerApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BodyMeasurementsTrackerApi.Models.Entities.BodyMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Biceps")
                        .HasColumnType("double precision");

                    b.Property<double>("BodyFatPercentage")
                        .HasColumnType("double precision");

                    b.Property<double>("BodyWeight")
                        .HasColumnType("double precision");

                    b.Property<double?>("Calves")
                        .HasColumnType("double precision");

                    b.Property<double?>("Chest")
                        .HasColumnType("double precision");

                    b.Property<double?>("Forearm")
                        .HasColumnType("double precision");

                    b.Property<double?>("Hips")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("MeasuredDate")
                        .HasColumnType("date");

                    b.Property<double?>("Neck")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ProgressPicture")
                        .HasColumnType("text");

                    b.Property<double?>("Shoulder")
                        .HasColumnType("double precision");

                    b.Property<double?>("Thighs")
                        .HasColumnType("double precision");

                    b.Property<double?>("Waist")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("BodyMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
